services:
#POSTGRESQL
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    restart: unless-stopped
