services:
  db:
    image: postgres:17
    env_file:
      - ./postgresql/.env
    volumes:
      - ./postgresql/db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - ${APP_PORT:-3031}:3001
      - 9229:9229 # for debugging
    command: sh -c "/app/start.sh"
    depends_on:
      db:
        condition: service_healthy

networks:
  isolated_network:
    driver: bridge
